### ISSUE TITLE
ERROR in Unexpected token {

### ISSUE THREAD

**Issue by litinskii** [styleguidist/example#1]
ERROR in Unexpected token {
 @ ./~/react-styleguidist/src/index.js 40:18-48 81:1-84:3
Child html-webpack-plugin for "index.html":

Get this error while try to start example.

**Comment by sapegin** [comment]
Can’t reproduce it. Did you change the style guide config?

**Comment by litinskii** [comment]
Hi. I can reproduce it while using node v5.7.0, if switch to 7.0.0 and all works fine, actually I don't is this an issue? So I will close because this work fro me. Thanks =)

**Comment by sapegin** [comment]
That‘s strange. Works for me with Node 4.6.2 and 5.12.0.

**Comment by benrobertsonio** [comment]
I was getting this same error with node 5.11.0. Switching to 7.0.0 resolved the issue for me.

**Comment by sapegin** [comment]
Should be fixed in 4.4.3.

**Comment by MarvanN** [comment]
I was getting this same error with node 16.13.2
